name: Update README timestamp

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Last Updated
        run: |
          TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          # Replace the placeholder on README.md with the new timestamp
          perl -0777 -pe "s/Last updated: <!--LAST-UPDATED-->.*$/Last updated: <!--LAST-UPDATED--> $TIMESTAMP/" -i README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README last updated timestamp" || echo "No changes to commit"
          git push
      - name: Done
        run: echo "README timestamp updated (if changed)."
